ECHO OFF
set TS_FILE_NAME=%1
set FILE_NAME=%TS_FILE_NAME:~0,-3%
set JS_FILE_NAME=%FILE_NAME%.js

ECHO ON && ECHO. && ECHO COMPILING FILE : %TS_FILE_NAME% && tsc %TS_FILE_NAME%  &&  ECHO RUNNING FILE : %JS_FILE_NAME% && node %JS_FILE_NAME% && DEL *.js